services:
  - type: web
    name: ctfd
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "wsgi:app" --bind 0.0.0.0:$PORT --workers 1
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: WORKERS
        value: "1"
      - key: SKIP_DB_PING
        value: "true"
    disk:
      name: ctfd-uploads
      mountPath: /var/uploads
      sizeGB: 1

